import "../styles/globals.css";
import type { AppProps } from "next/app";
import { Fragment } from "react";
import Head from "next/head";
import "../styles/helpers.css";
import { DarkTheme, LightTheme } from "../constants";
import { ThemeProvider } from "styled-components";
import ThemeContextProvider, { ThemeContext } from "../context/themeContext";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>Edson Ntwali- Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeContextProvider>
        <ThemeContext.Consumer>
          {(context) => {
            const { theme } = context;
            return (
              <ThemeProvider
                theme={
                  theme === "light"
                    ? LightTheme
                    : theme === "dark"
                    ? DarkTheme
                    : LightTheme
                }
              >
                <Component {...pageProps} />
              </ThemeProvider>
            );
          }}
        </ThemeContext.Consumer>
      </ThemeContextProvider>
    </Fragment>
  );
}
export default MyApp;
